### ISSUE TITLE
Missing/No license

### ISSUE THREAD

**Issue by RustyStriker** [henryksloan/sugarcubes#24]
Under what license is sugarcubes distributed?

**Comment by henryksloan** [comment]
Hi @RustyStriker, thank you for bringing this up. I decided to distribute Sugarcubes under a GPLv3 license. I've added the corresponding `LICENSE` file to the repo.

**Comment by RustyStriker** [comment]
Exciting, but as tho sugarcubes can be distributed as a web app i would highly suggest using AGPL instead

**Comment by henryksloan** [comment]
Good catch. I agree that fits the project better, so I've changed the license.
